resources:
  jobs:
    taxi_nyc_pipeline:
      name: ifood-taxi-nyc-${bundle.target}
      max_concurrent_runs: 1
      tags:
        project: ifood-case
        layer: medallion-4

      tasks:
        # YELLOW: ingestion in parallel with green
        - task_key: download_yellow
          notebook_task:
            notebook_path: ../src/00_download_landing.py
            base_parameters:
              taxi_type: "yellow"
              catalog: ${var.catalog}

        - task_key: bronze_yellow
          depends_on:
            - task_key: download_yellow
          notebook_task:
            notebook_path: ../src/01_landing_to_bronze.py
            base_parameters:
              taxi_type: "yellow"
              catalog: ${var.catalog}

        - task_key: silver_yellow
          depends_on:
            - task_key: bronze_yellow
          notebook_task:
            notebook_path: ../src/02_bronze_to_silver.py
            base_parameters:
              taxi_type: "yellow"
              catalog: ${var.catalog}

        # GREEN: ingestion in parallel with yellow
        - task_key: download_green
          notebook_task:
            notebook_path: ../src/00_download_landing.py
            base_parameters:
              taxi_type: "green"
              catalog: ${var.catalog}

        - task_key: bronze_green
          depends_on:
            - task_key: download_green
          notebook_task:
            notebook_path: ../src/01_landing_to_bronze.py
            base_parameters:
              taxi_type: "green"
              catalog: ${var.catalog}

        - task_key: silver_green
          depends_on:
            - task_key: bronze_green
          notebook_task:
            notebook_path: ../src/02_bronze_to_silver.py
            base_parameters:
              taxi_type: "green"
              catalog: ${var.catalog}

        # GOLD: converge yellow + green
        - task_key: gold_dimensions
          depends_on:
            - task_key: silver_yellow
            - task_key: silver_green
          notebook_task:
            notebook_path: ../src/03_gold_dimensions.py
            base_parameters:
              catalog: ${var.catalog}

        - task_key: gold_facts
          depends_on:
            - task_key: gold_dimensions
          notebook_task:
            notebook_path: ../src/04_gold_facts.py
            base_parameters:
              catalog: ${var.catalog}

        - task_key: gold_aggregates
          depends_on:
            - task_key: gold_facts
          notebook_task:
            notebook_path: ../src/05_gold_aggregates.py
            base_parameters:
              catalog: ${var.catalog}
